// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippingPortal.Api.Data;

#nullable disable

namespace portal_backend_dotnet.Migrations
{
    [DbContext(typeof(ShippingPortalDbContext))]
    [Migration("20260731084719_AddClearance")]
    partial class AddClearance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Clearance.Clearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ClearanceCompleteDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CopyOfBlReceivedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeclarationNo")
                        .HasColumnType("longtext");

                    b.Property<string>("LcNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("OriginalShipmentSetReceivedDate")
                        .HasColumnType("date");

                    b.Property<int>("Route")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("Clearances");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Clearance.ClearanceSlaSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MilestoneKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TargetDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClearanceSlaSettings");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Identity.UserBusinessUnitAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("UserId", "BusinessUnitId")
                        .IsUnique();

                    b.ToTable("UserBusinessUnitAccess");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.AcdCostSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerFclUsd")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("AcdCostSettings");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ApprovalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("ApprovalTypes");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.BusinessPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBrandManufacturer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsConsignee")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOffshoreEntity")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSupplier")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("BusinessPartners");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.BusinessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("BusinessUnits");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.Forwarder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Forwarders");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.FxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<decimal>("RateToUsd")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("FxRates");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.Incoterm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Incoterms");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ModelProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ModelProducts");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.OriginCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("OriginCountries");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.PaymentTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("PaymentTerms");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AffectsClr")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AffectsDxb")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ReceiverBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BankChargeRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ImChargeRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("TotalChargeRate")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("ReceiverBanks");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.SenderBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChargeRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MinimumChargeAed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("SenderBanks");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ShipmentDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultDurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFreeZone")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("ShipmentDestinations");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ShipmentMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("ShipmentModes");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ShippingLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("ShippingLines");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ShippingLineDemurrageTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AfterwardRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BuGroup")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ContainerSize")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("FirstPeriodRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("FreeDays")
                        .HasColumnType("int");

                    b.Property<int>("ShippingLineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShippingLineId");

                    b.ToTable("ShippingLineDemurrageTariffs");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.SpcRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<decimal>("EuroToSdgRate")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("SpcRates");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.Tenor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Tenors");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeasure");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Orders.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BrandManufacturerId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("BuPoDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("BuShippingBudget")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("int");

                    b.Property<int>("ConsigneeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int>("IncotermId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LatestShippingDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OffshorePoDate")
                        .HasColumnType("date");

                    b.Property<string>("OffshorePoNo")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateOnly?>("OrderExecutionDate")
                        .HasColumnType("date");

                    b.Property<int>("OriginCountryId")
                        .HasColumnType("int");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("ReceivedSignedPiDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SentSignedPiDate")
                        .HasColumnType("date");

                    b.Property<int>("ShipmentModeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierPaymentTermId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SupplierPiDate")
                        .HasColumnType("date");

                    b.Property<string>("SupplierPiNo")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalTypeId");

                    b.HasIndex("BrandManufacturerId");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("ConsigneeId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("IncotermId");

                    b.HasIndex("OriginCountryId");

                    b.HasIndex("PoNumber")
                        .IsUnique();

                    b.HasIndex("ShipmentModeId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("SupplierPaymentTermId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Orders.PurchaseOrderLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("ModelProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalUsd")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ModelProductId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("PurchaseOrderLineItems");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Orders.PurchaseOrderOffshorePartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessPartnerId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderOffshorePartners");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BlAwbDate")
                        .HasColumnType("date");

                    b.Property<string>("BlAwbNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("BlFreeDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("Eta")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Etd")
                        .HasColumnType("date");

                    b.Property<int>("Fcl20Count")
                        .HasColumnType("int");

                    b.Property<int>("Fcl40Count")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ShippingLineId")
                        .HasColumnType("int");

                    b.Property<bool>("Soc")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BlAwbNo")
                        .IsUnique();

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("ShippingLineId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentAcd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CostSettledDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly?>("ProcessDate")
                        .HasColumnType("date");

                    b.Property<string>("RefNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("ShipmentAcds");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentBanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CollectionAmountSettled")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("CollectionCurrencyId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CollectionDueDate")
                        .HasColumnType("date");

                    b.Property<string>("CollectionRefNo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("CollectionValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly?>("ImFormDate")
                        .HasColumnType("date");

                    b.Property<string>("ImFormNo")
                        .HasColumnType("longtext");

                    b.Property<bool>("NecessaryGoodType")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("OsDocDispatchDate")
                        .HasColumnType("date");

                    b.Property<int?>("OsDocDispatchedViaId")
                        .HasColumnType("int");

                    b.Property<string>("OsDocTrackingNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ReceiverBankCharges")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ReceivingBankId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RemainingDues")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SenderBankCharges")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("SenderBankId")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("TenorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectionCurrencyId");

                    b.HasIndex("OsDocDispatchedViaId");

                    b.HasIndex("ReceivingBankId");

                    b.HasIndex("SenderBankId");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.HasIndex("TenorId");

                    b.ToTable("ShipmentBankings");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentDraftDocuments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("FinalDraftConfirmedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FinalDraftReceivedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("InitialDraftReceivedDate")
                        .HasColumnType("date");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("ShipmentDraftDocuments");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentForwarder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualShippingCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ActualShippingCostUsd")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AmountSaved")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int?>("ForwarderId")
                        .HasColumnType("int");

                    b.Property<bool>("MarineInsurance")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ForwarderId");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("ShipmentForwarders");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ItemSubtotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PurchaseOrderLineItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("QtyInBl")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderLineItemId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentLineItems");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentMot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly?>("CostSettledDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OffshoreApprovedPiDate")
                        .HasColumnType("date");

                    b.Property<string>("OffshoreApprovedPiNumber")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("ProcessDate")
                        .HasColumnType("date");

                    b.Property<string>("RefNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("ShipmentMots");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentSsmo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ApplicationDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly?>("CostSettledDate")
                        .HasColumnType("date");

                    b.Property<string>("RefNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("ShipmentSsmos");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentSupplierFullSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("FsDispatchDate")
                        .HasColumnType("date");

                    b.Property<int?>("FsDispatchedViaId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FsReceivedDate")
                        .HasColumnType("date");

                    b.Property<string>("FsTrackingNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SupplierInvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("SupplierInvoiceNo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FsDispatchedViaId");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("ShipmentSupplierFullSets");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentSupplierPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AdvanceActualPaymentDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AdvanceDueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("AdvanceValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AdvanceValueUsd")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("BalanceUsd")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RemainingActualPaymentDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RemainingDueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("RemainingValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("RemainingValueUsd")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPaidUsd")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalValueUsd")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("ShipmentSupplierPayments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Clearance.Clearance", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Identity.UserBusinessUnitAccess", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Identity.ApplicationUser", "User")
                        .WithMany("BusinessUnitAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.Division", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.BusinessUnit", "BusinessUnit")
                        .WithMany("Divisions")
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessUnit");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.FxRate", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ModelProduct", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId");

                    b.HasOne("ShippingPortal.Api.Models.Lookups.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ShippingLineDemurrageTariff", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.ShippingLine", "ShippingLine")
                        .WithMany("DemurrageTariffs")
                        .HasForeignKey("ShippingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingLine");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Orders.PurchaseOrder", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.ApprovalType", "ApprovalType")
                        .WithMany()
                        .HasForeignKey("ApprovalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.BusinessPartner", "BrandManufacturer")
                        .WithMany()
                        .HasForeignKey("BrandManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.BusinessPartner", "Consignee")
                        .WithMany()
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.Incoterm", "Incoterm")
                        .WithMany()
                        .HasForeignKey("IncotermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.OriginCountry", "OriginCountry")
                        .WithMany()
                        .HasForeignKey("OriginCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.ShipmentMode", "ShipmentMode")
                        .WithMany()
                        .HasForeignKey("ShipmentModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.BusinessPartner", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.PaymentTerm", "SupplierPaymentTerm")
                        .WithMany()
                        .HasForeignKey("SupplierPaymentTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalType");

                    b.Navigation("BrandManufacturer");

                    b.Navigation("BusinessUnit");

                    b.Navigation("Consignee");

                    b.Navigation("Division");

                    b.Navigation("Incoterm");

                    b.Navigation("OriginCountry");

                    b.Navigation("ShipmentMode");

                    b.Navigation("Supplier");

                    b.Navigation("SupplierPaymentTerm");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Orders.PurchaseOrderLineItem", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.ModelProduct", "ModelProduct")
                        .WithMany()
                        .HasForeignKey("ModelProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Orders.PurchaseOrder", "PurchaseOrder")
                        .WithMany("LineItems")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("ModelProduct");

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductType");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Orders.PurchaseOrderOffshorePartner", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.BusinessPartner", "BusinessPartner")
                        .WithMany()
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Orders.PurchaseOrder", "PurchaseOrder")
                        .WithMany("OffshorePartners")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPartner");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.Shipment", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Orders.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.ShippingLine", "ShippingLine")
                        .WithMany()
                        .HasForeignKey("ShippingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("ShippingLine");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentAcd", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentBanking", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.Currency", "CollectionCurrency")
                        .WithMany()
                        .HasForeignKey("CollectionCurrencyId");

                    b.HasOne("ShippingPortal.Api.Models.Lookups.Courier", "OsDocDispatchedVia")
                        .WithMany()
                        .HasForeignKey("OsDocDispatchedViaId");

                    b.HasOne("ShippingPortal.Api.Models.Lookups.ReceiverBank", "ReceivingBank")
                        .WithMany()
                        .HasForeignKey("ReceivingBankId");

                    b.HasOne("ShippingPortal.Api.Models.Lookups.SenderBank", "SenderBank")
                        .WithMany()
                        .HasForeignKey("SenderBankId");

                    b.HasOne("ShippingPortal.Api.Models.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Lookups.Tenor", "Tenor")
                        .WithMany()
                        .HasForeignKey("TenorId");

                    b.Navigation("CollectionCurrency");

                    b.Navigation("OsDocDispatchedVia");

                    b.Navigation("ReceivingBank");

                    b.Navigation("SenderBank");

                    b.Navigation("Shipment");

                    b.Navigation("Tenor");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentDraftDocuments", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentForwarder", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("ShippingPortal.Api.Models.Lookups.Forwarder", "ForwarderEntity")
                        .WithMany()
                        .HasForeignKey("ForwarderId");

                    b.HasOne("ShippingPortal.Api.Models.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("ForwarderEntity");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentLineItem", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Orders.PurchaseOrderLineItem", "PurchaseOrderLineItem")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderLineItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingPortal.Api.Models.Shipments.Shipment", "Shipment")
                        .WithMany("LineItems")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrderLineItem");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentMot", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentSsmo", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentSupplierFullSet", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.Courier", "FsDispatchedVia")
                        .WithMany()
                        .HasForeignKey("FsDispatchedViaId");

                    b.HasOne("ShippingPortal.Api.Models.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FsDispatchedVia");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.ShipmentSupplierPayment", b =>
                {
                    b.HasOne("ShippingPortal.Api.Models.Lookups.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("ShippingPortal.Api.Models.Shipments.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Identity.ApplicationUser", b =>
                {
                    b.Navigation("BusinessUnitAccess");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.BusinessUnit", b =>
                {
                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Lookups.ShippingLine", b =>
                {
                    b.Navigation("DemurrageTariffs");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Orders.PurchaseOrder", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("OffshorePartners");
                });

            modelBuilder.Entity("ShippingPortal.Api.Models.Shipments.Shipment", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
